# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

unless User.exists?
  User.create!({name: 'Duy', age: 30, firstname: 'Chau'})
  User.create!({name: 'Nam', age: 29, firstname: 'Nguyen'})
  User.create!({name: 'Nhan', age: 22, firstname: 'Pham'})
  User.create!({name: 'Hoa', age: 16, firstname: 'Le'})
  User.create!({name: 'Mai', age: 19, firstname: 'Tran'})
  User.create!({name: 'Anh', age: 28, firstname: 'Vu'})
  User.create!({name: 'Truc', age: 18, firstname: 'Kasim'})
  User.create!({name: 'Nhi', age: 33, firstname: 'Bi'})
  User.create!({name: 'An', age: 29, firstname: 'Peter'})
  User.create!({name: 'Casey', age: 33, firstname: 'Aniel'})
  User.create!({name: 'Daniel', age: 35, firstname: 'Dang'})
  User.create!({name: 'John', age: 45, firstname: 'Duong'})
  User.create!({name: 'Lin', age: 29, firstname: 'Thai'})
  User.create!({name: 'Max', age: 34, firstname: 'Phan'})
  User.create!({name: 'Linda', age: 38, firstname: 'Ho'})
  User.create!({name: 'Onope', age: 48, firstname: 'Duong'})
  User.create!({name: 'Quyen', age: 43, firstname: 'Phan'})
  User.create!({name: 'Kim', age: 31, firstname: 'Tran'})
  User.create!({name: 'Huynh', age: 41, firstname: 'Duong'})
  User.create!({name: 'Ngoc', age: 61, firstname: 'Nguyen'})
  User.create!({name: 'Binh', age: 33, firstname: 'Thai'})
  User.create!({name: 'Nghia', age: 46, firstname: 'Phan'})
  User.create!({name: 'Emma', age: 23, firstname: 'Duong'})
  User.create!({name: 'Ferdinal', age: 27, firstname: 'Dang'})
  User.create!({name: 'George', age: 15, firstname: 'Dang'})
  User.create!({name: 'Hanah', age: 35, firstname: 'Aniel'})
  User.create!({name: 'Iris', age: 36, firstname: 'Nguyen'})
  User.create!({name: 'Jolie', age: 29, firstname: 'Nguyen'})
  User.create!({name: 'Rosep', age: 37, firstname: 'Thai'})
  User.create!({name: 'Tina', age: 19, firstname: 'Peter'})
  User.create!({name: 'Zo', age: 29, firstname: 'Tran'})
  User.create!({name: 'ABC', age: 27, firstname: 'Peter'})
end

unless Member.exists?
  Member.create!({user_id: 1, address:'123 LTK', full_name: 'Van Peter'})
  Member.create!({user_id: 2, address:'44 LTK', full_name: 'John Lennon'})
  Member.create!({user_id: 3, address:'23 LTK', full_name: 'Michael Owen'})
  Member.create!({user_id: 4, address:'3 LTK', full_name: 'Victor Hugo'})
  Member.create!({user_id: 5, address:'55 LTK', full_name: 'Leonardo de Vincy'})
  Member.create!({user_id: 6, address:'11 LTK', full_name: 'Hans Vitingus'})
  Member.create!({user_id: 7, address:'89 LTK', full_name: 'Jan Orgense'})
  Member.create!({user_id: 8, address:'67 LTK', full_name: 'Carina Miley'})
  Member.create!({user_id: 9, address:'12 LTK', full_name: 'William Serena'})
  Member.create!({user_id: 10, address:'78 LTK', full_name: 'ABC DEF'})

  Member.create!({user_id: 11, address:'44 LTK', full_name: 'Van Peter'})
  Member.create!({user_id: 12, address:'22 LTK', full_name: 'John Lennon'})
  Member.create!({user_id: 13, address:'12 LTK', full_name: 'Michael Owen'})
  Member.create!({user_id: 14, address:'43 LTK', full_name: 'Victor Hugo'})
  Member.create!({user_id: 15, address:'23 LTK', full_name: 'Leonardo de Vincy'})
  Member.create!({user_id: 16, address:'66 LTK', full_name: 'Hans Vitingus'})
  Member.create!({user_id: 17, address:'676 LTK', full_name: 'Jan Orgense'})
  Member.create!({user_id: 18, address:'221 LTK', full_name: 'Carina Miley'})
  Member.create!({user_id: 19, address:'434 LTK', full_name: 'William Serena'})
  Member.create!({user_id: 20, address:'342 LTK', full_name: 'ABC DEF'})

  Member.create!({user_id: 21, address:'312 LTK', full_name: 'Van Peter'})
  Member.create!({user_id: 22, address:'342 LTK', full_name: 'John Lennon'})
  Member.create!({user_id: 23, address:'453 LTK', full_name: 'Michael Owen'})
  Member.create!({user_id: 24, address:'34A LTK', full_name: 'Victor Hugo'})
  Member.create!({user_id: 25, address:'53DS LTK', full_name: 'Leonardo de Vincy'})
  Member.create!({user_id: 26, address:'ERT4 LTK', full_name: 'Hans Vitingus'})
  Member.create!({user_id: 27, address:'453F LTK', full_name: 'Jan Orgense'})
  Member.create!({user_id: 28, address:'34D LTK', full_name: 'Carina Miley'})
  Member.create!({user_id: 29, address:'43SSA LTK', full_name: 'William Serena'})
  Member.create!({user_id: 30, address:'5654D LTK', full_name: 'ABC DEF 30'})

  Member.create!({user_id: 31, address:'2423DF LTK', full_name: 'William Serena 31'})
  Member.create!({user_id: 32, address:'E65S LTK', full_name: 'ABC DEF 32'})
end

unless Patient.exists?
  Patient.create!({name: 'Patient 1', birthday:'1987/04/21', address:'312 LTT'})
  Patient.create!({name: 'Patient 2', birthday:'1984/04/22', address:'23S TNK'})
  Patient.create!({name: 'Patient 3', birthday:'1986/04/23', address:'E65S TNK'})
  Patient.create!({name: 'Patient 4', birthday:'1987/04/24', address:'32S TNK'})
  Patient.create!({name: 'Patient 5', birthday:'1988/04/26', address:'E65S LRY'})
  Patient.create!({name: 'Patient 6', birthday:'1989/04/28', address:'A33S LRY'})
  Patient.create!({name: 'Patient 7', birthday:'1984/04/22', address:'E65S LRY'})
  Patient.create!({name: 'Patient 8', birthday:'1981/04/21', address:'312 LTT'})
  Patient.create!({name: 'Patient 9', birthday:'1983/04/01', address:'67 GTY'})
  Patient.create!({name: 'Patient 10', birthday:'1983/04/10', address:'E65S GTYT'})
  Patient.create!({name: 'Patient 11', birthday:'1984/04/11', address:'325S GTYT'})
  Patient.create!({name: 'Patient 12', birthday:'1985/04/23', address:'E65S LTT'})
  Patient.create!({name: 'Patient 13', birthday:'1986/04/12', address:'A33S FTT'})
  Patient.create!({name: 'Patient 14', birthday:'1987/04/21', address:'E65S FTT'})
  Patient.create!({name: 'Patient 15', birthday:'1989/04/22', address:'312 FTT'})
  Patient.create!({name: 'Patient 16', birthday:'1981/04/09', address:'67 LTT'})
  Patient.create!({name: 'Patient 17', birthday:'1982/04/07', address:'E65S LTT'})
  Patient.create!({name: 'Patient 18', birthday:'1983/04/05', address:'32S MCS'})
  Patient.create!({name: 'Patient 19', birthday:'1984/04/05', address:'E65S MCS'})
  Patient.create!({name: 'Patient 20', birthday:'1985/04/06', address:'A33S MCS'})
  Patient.create!({name: 'Patient 21', birthday:'1986/04/17', address:'E65S LTT'})
  Patient.create!({name: 'Patient 22', birthday:'1987/04/18', address:'E65S LTT'})
  Patient.create!({name: 'Patient 23', birthday:'1988/04/19', address:'67S HFB'})
  Patient.create!({name: 'Patient 24', birthday:'1988/04/20', address:'E65S HFB'})
  Patient.create!({name: 'Patient 25', birthday:'1989/04/21', address:'E65S HFB'})
  Patient.create!({name: 'Patient 26', birthday:'1989/04/22', address:'E65S LTT'})
  Patient.create!({name: 'Patient 27', birthday:'1980/04/21', address:'22F PFT'})
  Patient.create!({name: 'Patient 28', birthday:'1981/04/23', address:'22F PFT'})
  Patient.create!({name: 'Patient 29', birthday:'1982/04/25', address:'E65S PFT'})
end

unless Physician.exists?
  Physician.create!({name: 'Physician 1'})
  Physician.create!({name: 'Physician 2'})
  Physician.create!({name: 'Physician 3'})
  Physician.create!({name: 'Physician 4'})
  Physician.create!({name: 'Physician 5'})
end

unless Appointment.exists?
  Appointment.create!({physician_id: 1, patient_id: 1, appointment_date: '12/04/2016'})
  Appointment.create!({physician_id: 1, patient_id: 1, appointment_date: '17/05/2016'})
  Appointment.create!({physician_id: 1, patient_id: 1, appointment_date: '22/09/2016'})
  Appointment.create!({physician_id: 1, patient_id: 2, appointment_date: '12/04/2016'})
  Appointment.create!({physician_id: 1, patient_id: 3, appointment_date: '14/08/2016'})
  Appointment.create!({physician_id: 1, patient_id: 4, appointment_date: '17/04/2016'})
  Appointment.create!({physician_id: 1, patient_id: 5, appointment_date: '12/08/2016'})
  Appointment.create!({physician_id: 1, patient_id: 6, appointment_date: '14/04/2016'})
  Appointment.create!({physician_id: 1, patient_id: 7, appointment_date: '17/08/2016'})
  Appointment.create!({physician_id: 1, patient_id: 8, appointment_date: '12/04/2016'})
  Appointment.create!({physician_id: 1, patient_id: 9, appointment_date: '14/04/2016'})
  
  Appointment.create!({physician_id: 2, patient_id: 1, appointment_date: '13/04/2016'})
  Appointment.create!({physician_id: 2, patient_id: 10, appointment_date: '14/05/2016'})
  Appointment.create!({physician_id: 2, patient_id: 11, appointment_date: '19/02/2016'})
  Appointment.create!({physician_id: 2, patient_id: 12, appointment_date: '13/04/2016'})
  Appointment.create!({physician_id: 2, patient_id: 12, appointment_date: '23/04/2016'})
  Appointment.create!({physician_id: 2, patient_id: 13, appointment_date: '14/05/2016'})
  Appointment.create!({physician_id: 2, patient_id: 14, appointment_date: '19/02/2016'})
  
  Appointment.create!({physician_id: 3, patient_id: 1, appointment_date: '19/02/2016'})
  Appointment.create!({physician_id: 3, patient_id: 2, appointment_date: '19/02/2016'})
  Appointment.create!({physician_id: 3, patient_id: 12, appointment_date: '13/04/2016'})
  Appointment.create!({physician_id: 3, patient_id: 12, appointment_date: '23/05/2016'})
  Appointment.create!({physician_id: 3, patient_id: 12, appointment_date: '23/06/2016'})
  Appointment.create!({physician_id: 3, patient_id: 13, appointment_date: '14/05/2016'})
  Appointment.create!({physician_id: 3, patient_id: 14, appointment_date: '19/02/2016'})
  Appointment.create!({physician_id: 3, patient_id: 21, appointment_date: '19/02/2016'})
  Appointment.create!({physician_id: 3, patient_id: 22, appointment_date: '19/02/2016'})
  Appointment.create!({physician_id: 3, patient_id: 12, appointment_date: '13/04/2016'})
  Appointment.create!({physician_id: 3, patient_id: 23, appointment_date: '14/05/2016'})
  Appointment.create!({physician_id: 3, patient_id: 24, appointment_date: '19/02/2016'})
  
  
end