# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

unless User.exists?
  User.create!({name: 'Duy', age: 30, firstname: 'Chau'})
  User.create!({name: 'Nam', age: 29, firstname: 'Nguyen'})
  User.create!({name: 'Nhan', age: 22, firstname: 'Pham'})
  User.create!({name: 'Hoa', age: 16, firstname: 'Le'})
  User.create!({name: 'Mai', age: 19, firstname: 'Tran'})
  User.create!({name: 'Anh', age: 28, firstname: 'Vu'})
  User.create!({name: 'Truc', age: 18, firstname: 'Kasim'})
  User.create!({name: 'Nhi', age: 33, firstname: 'Bi'})
  User.create!({name: 'An', age: 29, firstname: 'Peter'})
  User.create!({name: 'Casey', age: 33, firstname: 'Aniel'})
  User.create!({name: 'Daniel', age: 35, firstname: 'Dang'})
  User.create!({name: 'John', age: 45, firstname: 'Duong'})
  User.create!({name: 'Lin', age: 29, firstname: 'Thai'})
  User.create!({name: 'Max', age: 34, firstname: 'Phan'})
  User.create!({name: 'Linda', age: 38, firstname: 'Ho'})
  User.create!({name: 'Onope', age: 48, firstname: 'Duong'})
  User.create!({name: 'Quyen', age: 43, firstname: 'Phan'})
  User.create!({name: 'Kim', age: 31, firstname: 'Tran'})
  User.create!({name: 'Huynh', age: 41, firstname: 'Duong'})
  User.create!({name: 'Ngoc', age: 61, firstname: 'Nguyen'})
  User.create!({name: 'Binh', age: 33, firstname: 'Thai'})
  User.create!({name: 'Nghia', age: 46, firstname: 'Phan'})
  User.create!({name: 'Emma', age: 23, firstname: 'Duong'})
  User.create!({name: 'Ferdinal', age: 27, firstname: 'Dang'})
  User.create!({name: 'George', age: 15, firstname: 'Dang'})
  User.create!({name: 'Hanah', age: 35, firstname: 'Aniel'})
  User.create!({name: 'Iris', age: 36, firstname: 'Nguyen'})
  User.create!({name: 'Jolie', age: 29, firstname: 'Nguyen'})
  User.create!({name: 'Rosep', age: 37, firstname: 'Thai'})
  User.create!({name: 'Tina', age: 19, firstname: 'Peter'})
  User.create!({name: 'Zo', age: 29, firstname: 'Tran'})
  User.create!({name: 'ABC', age: 27, firstname: 'Peter'})
end

unless Member.exists?
  Member.create!({user_id: 1, address:'123 LTK', full_name: 'Van Peter'})
  Member.create!({user_id: 2, address:'44 LTK', full_name: 'John Lennon'})
  Member.create!({user_id: 3, address:'23 LTK', full_name: 'Michael Owen'})
  Member.create!({user_id: 4, address:'3 LTK', full_name: 'Victor Hugo'})
  Member.create!({user_id: 5, address:'55 LTK', full_name: 'Leonardo de Vincy'})
  Member.create!({user_id: 6, address:'11 LTK', full_name: 'Hans Vitingus'})
  Member.create!({user_id: 7, address:'89 LTK', full_name: 'Jan Orgense'})
  Member.create!({user_id: 8, address:'67 LTK', full_name: 'Carina Miley'})
  Member.create!({user_id: 9, address:'12 LTK', full_name: 'William Serena'})
  Member.create!({user_id: 10, address:'78 LTK', full_name: 'ABC DEF'})

  Member.create!({user_id: 11, address:'44 LTK', full_name: 'Van Peter'})
  Member.create!({user_id: 12, address:'22 LTK', full_name: 'John Lennon'})
  Member.create!({user_id: 13, address:'12 LTK', full_name: 'Michael Owen'})
  Member.create!({user_id: 14, address:'43 LTK', full_name: 'Victor Hugo'})
  Member.create!({user_id: 15, address:'23 LTK', full_name: 'Leonardo de Vincy'})
  Member.create!({user_id: 16, address:'66 LTK', full_name: 'Hans Vitingus'})
  Member.create!({user_id: 17, address:'676 LTK', full_name: 'Jan Orgense'})
  Member.create!({user_id: 18, address:'221 LTK', full_name: 'Carina Miley'})
  Member.create!({user_id: 19, address:'434 LTK', full_name: 'William Serena'})
  Member.create!({user_id: 20, address:'342 LTK', full_name: 'ABC DEF'})

  Member.create!({user_id: 21, address:'312 LTK', full_name: 'Van Peter'})
  Member.create!({user_id: 22, address:'342 LTK', full_name: 'John Lennon'})
  Member.create!({user_id: 23, address:'453 LTK', full_name: 'Michael Owen'})
  Member.create!({user_id: 24, address:'34A LTK', full_name: 'Victor Hugo'})
  Member.create!({user_id: 25, address:'53DS LTK', full_name: 'Leonardo de Vincy'})
  Member.create!({user_id: 26, address:'ERT4 LTK', full_name: 'Hans Vitingus'})
  Member.create!({user_id: 27, address:'453F LTK', full_name: 'Jan Orgense'})
  Member.create!({user_id: 28, address:'34D LTK', full_name: 'Carina Miley'})
  Member.create!({user_id: 29, address:'43SSA LTK', full_name: 'William Serena'})
  Member.create!({user_id: 30, address:'5654D LTK', full_name: 'ABC DEF 30'})

  Member.create!({user_id: 31, address:'2423DF LTK', full_name: 'William Serena 31'})
  Member.create!({user_id: 32, address:'E65S LTK', full_name: 'ABC DEF 32'})
end